"""ReKep runtime: constraint-driven staged execution on the MuJoCo env.

Mirrors the reference ``main.py`` control loop (subgoal solve -> path solve ->
execute -> grasp/release -> backtrack) but is decoupled from OmniGibson and
uses the reference solvers + our MuJoCo env. Constraint programs are either
generated by the VLM (reference ``constraint_generation``) or by a deterministic
template (used for offline/deterministic acceptance without an API key).
"""

from __future__ import annotations

import json
import time
import uuid
from dataclasses import dataclass, field
from typing import Any, Callable

import numpy as np

from . import refimpl
from .sandbox import load_functions


@dataclass
class RuntimeConfig:
    sdf_voxel_size: float = 0.02
    action_steps_per_iter: int = 8
    constraint_tolerance: float = 0.10
    grasp_depth: float = 0.03
    interpolate_pos_step_size: float = 0.05
    interpolate_rot_step_size: float = 0.34
    max_iterations: int = 60
    seed: int = 0
    force_tool_down: bool = True
    subgoal_sampling_maxfun: int = 2000
    path_sampling_maxfun: int = 2000
    minimizer_maxiter: int = 100
    extra: dict[str, Any] = field(default_factory=dict)


class IKAdapter:
    """Expose env.solve_ik_result as ``.solve`` for the reference solvers."""

    def __init__(self, env):
        self.env = env

    def solve(self, target_pose_homo, position_tolerance=0.01, orientation_tolerance=0.05,
              position_weight=1.0, orientation_weight=0.05, max_iterations=150,
              initial_joint_pos=None):
        return self.env.solve_ik_result(
            target_pose_homo,
            position_tolerance=position_tolerance,
            orientation_tolerance=orientation_tolerance,
            position_weight=position_weight,
            orientation_weight=orientation_weight,
            max_iterations=max_iterations,
            initial_joint_pos=initial_joint_pos,
        )


def _solver_configs(env, cfg: RuntimeConfig):
    bmin, bmax = env.bounds_min.tolist(), env.bounds_max.tolist()
    subgoal = {
        "bounds_min": bmin,
        "bounds_max": bmax,
        "sampling_maxfun": cfg.subgoal_sampling_maxfun,
        "max_collision_points": 60,
        "constraint_tolerance": 1e-4,
        "minimizer_options": {"maxiter": cfg.minimizer_maxiter},
        "grasp_axis_local": [1.0, 0.0, 0.0],
        "grasp_preferred_world_dir": [0.0, 0.0, -1.0],
    }
    path = {
        "bounds_min": bmin,
        "bounds_max": bmax,
        "opt_pos_step_size": 0.20,
        "opt_rot_step_size": 0.78,
        "opt_interpolate_pos_step_size": 0.03,
        "opt_interpolate_rot_step_size": 0.20,
        "max_collision_points": 60,
        "sampling_maxfun": cfg.path_sampling_maxfun,
        "constraint_tolerance": 1e-4,
        "minimizer_options": {"maxiter": cfg.minimizer_maxiter},
    }
    return subgoal, path


class ReKepRuntime:
    def __init__(self, env, config: RuntimeConfig | None = None):
        self.env = env
        self.config = config or RuntimeConfig()
        refimpl.ensure_reference_on_path()
        import transform_utils as T
        import utils as ref_utils

        self._T = T
        self._ref_utils = ref_utils
        self.ik = None
        self.subgoal_solver = None
        self.path_solver = None
        if env is not None:
            self._build_solvers()

    def _build_solvers(self) -> None:
        import path_solver as path_solver_mod
        import subgoal_solver as subgoal_solver_mod

        subgoal_cfg, path_cfg = _solver_configs(self.env, self.config)
        reset = self.env.reset_joint_positions()
        self.ik = IKAdapter(self.env)
        self.subgoal_solver = subgoal_solver_mod.SubgoalSolver(subgoal_cfg, self.ik, reset)
        self.path_solver = path_solver_mod.PathSolver(path_cfg, self.ik, reset)

    # ------------------------------------------------------------------ plan
    def make_template_program(self, snapshot: dict, instruction: str) -> dict:
        """Deterministic 3-stage pick/place program from a perception snapshot."""
        kps = snapshot["keypoints"]
        cube_idx = _role_index(kps, "pick_cube")
        place_idx = _role_index(kps, "place_zone")
        prog = (
            "num_stages = 3\n"
            "def stage1_subgoal_constraint1(end_effector, keypoints):\n"
            f"    return np.linalg.norm(end_effector - keypoints[{cube_idx}])\n"
            "def stage2_subgoal_constraint1(end_effector, keypoints):\n"
            f"    return np.linalg.norm(keypoints[{cube_idx}] - keypoints[{place_idx}])\n"
            "def stage2_path_constraint1(end_effector, keypoints):\n"
            f"    return get_grasping_cost_by_keypoint_idx({cube_idx})\n"
            "def stage3_subgoal_constraint1(end_effector, keypoints):\n"
            f"    return np.linalg.norm(keypoints[{cube_idx}] - keypoints[{place_idx}])\n"
            f"grasp_keypoints = [{cube_idx}, -1, -1]\n"
            f"release_keypoints = [-1, -1, {cube_idx}]\n"
        )
        return self._program_from_text(prog, snapshot, instruction, source="template")

    def _program_from_text(self, text: str, snapshot: dict, instruction: str, *, source: str,
                          vlm_trace: str | None = None) -> dict:
        import re

        num_stages = int(re.search(r"num_stages\s*=\s*(\d+)", text).group(1))
        grasp = _parse_list(text, "grasp_keypoints", num_stages)
        release = _parse_list(text, "release_keypoints", num_stages)
        # split functions by stage/type
        stage_funcs: list[dict[str, str]] = [
            {"subgoal": "", "path": ""} for _ in range(num_stages)
        ]
        current: list[str] = []
        name = None
        for line in text.splitlines():
            if line.startswith("def "):
                if name is not None:
                    _append_group(stage_funcs, name, current)
                name = line.split("(")[0].replace("def ", "").strip()
                current = [line]
            elif name is not None:
                current.append(line)
                if line.strip().startswith("return "):
                    _append_group(stage_funcs, name, current)
                    name = None
                    current = []
        core = {
            "instruction": instruction,
            "observation_id": snapshot.get("observation_id"),
            "num_stages": num_stages,
            "grasp_keypoints": grasp,
            "release_keypoints": release,
            "keypoints": snapshot["keypoints"],
            "init_keypoint_positions": [k["position_m"] for k in snapshot["keypoints"]],
            "stages": [
                {
                    "stage": i + 1,
                    "subgoal_constraints": stage_funcs[i]["subgoal"],
                    "path_constraints": stage_funcs[i]["path"],
                    "grasp_keypoint": grasp[i],
                    "release_keypoint": release[i],
                }
                for i in range(num_stages)
            ],
            "source": source,
        }
        core["plan_id"] = f"plan_{uuid.uuid4().hex}"
        core["created_timestamp_ns"] = str(time.time_ns())
        if vlm_trace:
            core["vlm_trace"] = vlm_trace
        core["plan_digest"] = _digest({k: v for k, v in core.items() if k != "plan_digest"})
        return core

    def plan(self, instruction: str, snapshot: dict, *, source: str = "template") -> dict:
        if source == "vlm":
            return self._plan_vlm(instruction, snapshot)
        return self.make_template_program(snapshot, instruction)

    def _plan_vlm(self, instruction: str, snapshot: dict) -> dict:
        import constraint_generation

        gen = constraint_generation.ConstraintGenerator(
            {"model": "gpt-5.4", "temperature": 0.0, "max_tokens": 16384}
        )
        # Ground the model on the exact keypoint IDs (mirrors the reference
        # real-path index guard). Without this the VLM remaps IDs arbitrarily.
        keypoints = snapshot["keypoints"]
        guard_lines = ["Use exact keypoint IDs from this table. Never remap ID meanings:"]
        for k in keypoints:
            guard_lines.append(
                f"- id {k['index']}: object={k.get('object', 'unknown')}, "
                f"position_m={[round(float(x), 3) for x in k['position_m']]}"
            )
        grasp_id = next(
            (k["index"] for k in keypoints if k.get("object") == "pick_cube"), None
        )
        if grasp_id is not None:
            guard_lines.append(
                f"- The first grasping stage must grasp the pick_cube keypoint id {grasp_id}."
            )
        guard = "\n".join(guard_lines)
        _orig_build_prompt = gen._build_prompt

        def _build_prompt_guarded(image_path, instruction):
            messages, text = _orig_build_prompt(image_path, instruction)
            suffix = "\n\n## Additional Hard Constraints\n" + guard + "\n"
            for message in messages:
                if isinstance(message.get("content"), list):
                    for part in message["content"]:
                        if part.get("type") == "text":
                            part["text"] = part["text"] + suffix
            return messages, text + suffix

        gen._build_prompt = _build_prompt_guarded
        metadata = {
            "init_keypoint_positions": [k["position_m"] for k in snapshot["keypoints"]],
            "num_keypoints": len(snapshot["keypoints"]),
            "task_schema": {"keypoints": snapshot["keypoints"]},
        }
        import cv2

        rgb = cv2.imread(snapshot["overlay_path"]) if snapshot.get("overlay_path") else None
        if rgb is None:
            raise RuntimeError("plan(source=vlm) requires an overlay image in the snapshot")
        task_dir = gen.generate(rgb, instruction, metadata)
        with open(f"{task_dir}/metadata.json") as f:
            meta = json.load(f)
        text_parts = []
        num_stages = int(meta["num_stages"])
        for i in range(1, num_stages + 1):
            for kind in ("subgoal", "path"):
                p = f"{task_dir}/stage{i}_{kind}_constraints.txt"
                try:
                    with open(p) as f:
                        text_parts.append(f.read())
                except FileNotFoundError:
                    pass
        text = "\n".join(text_parts)
        text += f"\nnum_stages = {num_stages}\n"
        text += f"grasp_keypoints = {meta['grasp_keypoints']}\n"
        text += f"release_keypoints = {meta['release_keypoints']}\n"
        return self._program_from_text(text, snapshot, instruction, source="vlm",
                                       vlm_trace=f"{task_dir}/vlm_trace.json")

    # --------------------------------------------------------------- execute
    def execute(self, program: dict, *, cancel=None, progress: Callable[[dict], None] | None = None,
                allow_motion: bool = True) -> dict:
        env = self.env
        cfg = self.config
        np.random.seed(cfg.seed)
        import torch

        torch.manual_seed(cfg.seed)

        num_stages = int(program["num_stages"])
        grasp_kps = list(program["grasp_keypoints"])
        release_kps = list(program["release_keypoints"])
        init_kps = np.asarray(program["init_keypoint_positions"], dtype=float)
        # compile constraints in the sandbox, bound to the grasp set of each stage
        stage_fns = []
        for i, stage in enumerate(program["stages"]):
            stage_fns.append(
                {
                    "subgoal": _compile(stage["subgoal_constraints"]),
                    "path": _compile(stage["path_constraints"]),
                }
            )
        env.register_keypoints(init_kps)
        keypoint_movable_mask = np.zeros(len(init_kps) + 1, dtype=bool)
        keypoint_movable_mask[0] = True

        def fns_for(stage: int):
            # reference binds the grasping-cost function per constraint evaluation
            grasped = {
                int(grasp_kps[j - 1])
                for j in range(1, stage + 1)
                if grasp_kps[j - 1] != -1
            }
            sub = _compile(program["stages"][stage - 1]["subgoal_constraints"], grasped)
            pat = _compile(program["stages"][stage - 1]["path_constraints"], grasped)
            return sub, pat

        stage = 1
        first_iter = True
        action_queue: list[np.ndarray] = []
        phases: list[dict[str, Any]] = []
        started = time.monotonic()
        deadline = float("inf")  # caller enforces deadline via cancel
        while True:
            if cancel is not None and cancel.is_set():
                video = env.save_video()
                return {"status": "cancelled", "video": video, "stages": phases}
            scene_kps = env.get_keypoint_positions()
            keypoints = np.concatenate([[env.get_ee_pos()], scene_kps], axis=0)
            curr_ee_pose = env.get_ee_pose()
            curr_joint_pos = env.get_arm_joint_postions()
            sdf = env.get_sdf_voxels(cfg.sdf_voxel_size)
            collision = env.get_collision_points()
            is_grasp = grasp_kps[stage - 1] != -1
            is_release = release_kps[stage - 1] != -1
            # keypoints on grasped objects become movable in the optimization
            for i in range(1, len(keypoint_movable_mask)):
                keypoint_movable_mask[i] = env.is_grasping(env.get_object_by_keypoint(i - 1))

            sub_fns, pat_fns = fns_for(stage)
            # backtrack if current-stage path constraints are violated
            backtrack = False
            if stage > 1:
                for fn in pat_fns:
                    if float(fn(keypoints[0], keypoints[1:])) > cfg.constraint_tolerance:
                        backtrack = True
                        break
            if backtrack:
                new_stage = max(1, stage - 1)
                if cancel is not None and cancel.is_set():
                    continue
                stage = new_stage
                first_iter = True
                action_queue = []
                _progress(progress, {"phase": f"backtrack_to_stage_{stage}"})
                continue

            subgoal, dbg1 = self.subgoal_solver.solve(
                curr_ee_pose, keypoints, keypoint_movable_mask, sub_fns, pat_fns,
                sdf, collision, is_grasp, curr_joint_pos, from_scratch=first_iter,
            )
            subgoal_pose = np.asarray(subgoal, dtype=float)
            if is_grasp:
                homo = self._T.convert_pose_quat2mat(subgoal_pose)
                subgoal_pose = subgoal_pose.copy()
                subgoal_pose[:3] += homo[:3, :3] @ np.array([-cfg.grasp_depth / 2.0, 0.0, 0.0])
            path, dbg2 = self.path_solver.solve(
                curr_ee_pose, subgoal_pose, keypoints, keypoint_movable_mask, pat_fns,
                sdf, collision, curr_joint_pos, from_scratch=first_iter,
            )
            action_queue = self._process_path(path)
            first_iter = False

            count = 0
            while action_queue and count < cfg.action_steps_per_iter:
                if cancel is not None and cancel.is_set():
                    break
                act = action_queue.pop(0)
                if allow_motion:
                    if cfg.force_tool_down:
                        act = act.copy()
                        act[3:7] = env.tool_down_quat()
                    env.execute_action(act, precise=len(action_queue) == 0)
                count += 1
            if action_queue:
                continue
            # stage finished: grasp / release / advance
            if is_grasp:
                ok = self._grasp_action(grasp_kps[stage - 1], keypoints, cancel)
                phases.append({"phase": f"stage{stage}_grasp", "ok": bool(ok)})
                _progress(progress, {"phase": f"stage{stage}_grasp", "ok": bool(ok)})
                if not ok:
                    video = env.save_video()
                    return {
                        "status": "failed",
                        "error": f"grasp failed at stage {stage}",
                        "video": video,
                        "stages": phases,
                    }
            elif is_release:
                env.open_gripper()
                phases.append({"phase": f"stage{stage}_release", "ok": True})
                _progress(progress, {"phase": f"stage{stage}_release"})
            if stage == num_stages:
                env.sleep(0.3)
                video = env.save_video()
                cube_joint = env.cube_qposadr
                final_cube = env.data.qpos[cube_joint:cube_joint + 3].tolist()
                # verify the cube reached the place keypoint (no blind success)
                scene = env.get_keypoint_positions()
                place_idx = next(
                    (
                        int(k["index"])
                        for k in program["keypoints"]
                        if k.get("object") == "place_zone"
                    ),
                    0,
                )
                target = scene[place_idx]
                err = float(np.linalg.norm(np.asarray(final_cube) - target))
                ok = err < 0.06 and final_cube[2] < 0.06
                return {
                    "status": "succeeded" if ok else "failed",
                    "video": video,
                    "stages": phases,
                    "final_cube_position_m": final_cube,
                    "place_error_m": round(err, 4),
                    "elapsed_s": round(time.monotonic() - started, 2),
                }
            stage += 1
            first_iter = True

    def _grasp_action(self, grasp_keypoint: int, keypoints: np.ndarray, cancel) -> bool:
        env = self.env
        candidate = env.get_object_by_keypoint(int(grasp_keypoint))
        offsets = [(0.0, 0.0, 0.0), (0.0, 0.006, 0.0), (0.0, -0.006, 0.0), (-0.008, 0.0, 0.0)]
        for i, off in enumerate(offsets):
            if cancel is not None and cancel.is_set():
                return False
            if i > 0:
                # retreat, shift, and re-approach before closing again
                env.open_gripper()
            env.close_gripper()
            if env.is_grasping(candidate):
                return True
        return env.is_grasping(candidate)

    def _process_path(self, path_quat: np.ndarray) -> list[np.ndarray]:
        """Spline-densify a control-point path into action vectors with null gripper."""
        cfg = self.config
        full = np.concatenate([self.env.get_ee_pose().reshape(1, -1), path_quat], axis=0)
        num_steps = self._ref_utils.get_linear_interpolation_steps(
            full[0], full[-1], cfg.interpolate_pos_step_size, cfg.interpolate_rot_step_size
        )
        dense = self._ref_utils.spline_interpolate_poses(full, max(num_steps, 2))
        actions = np.zeros((dense.shape[0], 8))
        actions[:, :7] = dense
        actions[:, 7] = self.env.get_gripper_null_action()
        return [a for a in actions]


def _compile(text: str, grasped_keypoints=None):
    text = (text or "").strip()
    if not text:
        return []
    return load_functions(text, grasped_keypoints=grasped_keypoints, timeout_s=2.0)


def _progress(cb, data):
    if cb is not None:
        cb(data)


def _parse_list(text: str, name: str, num_stages: int) -> list[int]:
    import re

    m = re.search(rf"{name}\s*=\s*\[([^\]]*)\]", text)
    if not m:
        return [-1] * num_stages
    items = [x.strip() for x in m.group(1).split(",") if x.strip() != ""]
    vals = [int(x) for x in items]
    if len(vals) != num_stages:
        raise ValueError(f"{name} length {len(vals)} != num_stages {num_stages}")
    return vals


def _append_group(stage_funcs: list[dict[str, str]], name: str, lines: list[str]) -> None:
    import re

    m = re.match(r"stage(\d+)_(subgoal|path)", name)
    if not m:
        return
    stage_idx = int(m.group(1)) - 1
    kind = m.group(2)
    if 0 <= stage_idx < len(stage_funcs):
        stage_funcs[stage_idx][kind] = (stage_funcs[stage_idx][kind] + "\n" + "\n".join(lines)).strip()


def _role_index(keypoints: list[dict], object_name: str) -> int:
    for k in keypoints:
        if k.get("object") == object_name:
            return int(k["index"])
    # fall back to positional: cube is last, place zone is first
    return 0 if object_name == "place_zone" else len(keypoints) - 1


def _digest(value: Any) -> str:
    import hashlib

    return "sha256:" + hashlib.sha256(
        json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode()
    ).hexdigest()
